package com.logistics.model;

import java.util.Date;

import javax.xml.bind.annotation.XmlRootElement;

@XmlRootElement
public class Amenities {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column amenities.AmenitiyId
     *
     * @mbggenerated Wed May 27 11:34:25 PDT 2015
     */
    private Short amenitiyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column amenities.Amenity
     *
     * @mbggenerated Wed May 27 11:34:25 PDT 2015
     */
    private String amenity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column amenities.IsActive
     *
     * @mbggenerated Wed May 27 11:34:25 PDT 2015
     */
    private Boolean isActive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column amenities.CreatedBy
     *
     * @mbggenerated Wed May 27 11:34:25 PDT 2015
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column amenities.CreatedDate
     *
     * @mbggenerated Wed May 27 11:34:25 PDT 2015
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column amenities.ModifiedBy
     *
     * @mbggenerated Wed May 27 11:34:25 PDT 2015
     */
    private String modifiedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column amenities.ModifiedDate
     *
     * @mbggenerated Wed May 27 11:34:25 PDT 2015
     */
    private Date modifiedDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column amenities.AmenitiyId
     *
     * @return the value of amenities.AmenitiyId
     *
     * @mbggenerated Wed May 27 11:34:25 PDT 2015
     */
    public Short getAmenitiyId() {
        return amenitiyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column amenities.AmenitiyId
     *
     * @param amenitiyId the value for amenities.AmenitiyId
     *
     * @mbggenerated Wed May 27 11:34:25 PDT 2015
     */
    public void setAmenitiyId(Short amenitiyId) {
        this.amenitiyId = amenitiyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column amenities.Amenity
     *
     * @return the value of amenities.Amenity
     *
     * @mbggenerated Wed May 27 11:34:25 PDT 2015
     */
    public String getAmenity() {
        return amenity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column amenities.Amenity
     *
     * @param amenity the value for amenities.Amenity
     *
     * @mbggenerated Wed May 27 11:34:25 PDT 2015
     */
    public void setAmenity(String amenity) {
        this.amenity = amenity == null ? null : amenity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column amenities.IsActive
     *
     * @return the value of amenities.IsActive
     *
     * @mbggenerated Wed May 27 11:34:25 PDT 2015
     */
    public Boolean getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column amenities.IsActive
     *
     * @param isActive the value for amenities.IsActive
     *
     * @mbggenerated Wed May 27 11:34:25 PDT 2015
     */
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column amenities.CreatedBy
     *
     * @return the value of amenities.CreatedBy
     *
     * @mbggenerated Wed May 27 11:34:25 PDT 2015
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column amenities.CreatedBy
     *
     * @param createdBy the value for amenities.CreatedBy
     *
     * @mbggenerated Wed May 27 11:34:25 PDT 2015
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column amenities.CreatedDate
     *
     * @return the value of amenities.CreatedDate
     *
     * @mbggenerated Wed May 27 11:34:25 PDT 2015
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column amenities.CreatedDate
     *
     * @param createdDate the value for amenities.CreatedDate
     *
     * @mbggenerated Wed May 27 11:34:25 PDT 2015
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column amenities.ModifiedBy
     *
     * @return the value of amenities.ModifiedBy
     *
     * @mbggenerated Wed May 27 11:34:25 PDT 2015
     */
    public String getModifiedBy() {
        return modifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column amenities.ModifiedBy
     *
     * @param modifiedBy the value for amenities.ModifiedBy
     *
     * @mbggenerated Wed May 27 11:34:25 PDT 2015
     */
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy == null ? null : modifiedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column amenities.ModifiedDate
     *
     * @return the value of amenities.ModifiedDate
     *
     * @mbggenerated Wed May 27 11:34:25 PDT 2015
     */
    public Date getModifiedDate() {
        return modifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column amenities.ModifiedDate
     *
     * @param modifiedDate the value for amenities.ModifiedDate
     *
     * @mbggenerated Wed May 27 11:34:25 PDT 2015
     */
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
}